// <copyright file="CloudVariables.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudInt s_playerGold = new CloudInt("PlayerGold", PersistenceType.Latest, 0);

        public static int PlayerGold
        {
            get { return s_playerGold.Value; }
            set { s_playerGold.Value = value; }
        }

        private static readonly CloudInt s_playerDiamond = new CloudInt("PlayerDiamond", PersistenceType.Latest, 0);

        public static int PlayerDiamond
        {
            get { return s_playerDiamond.Value; }
            set { s_playerDiamond.Value = value; }
        }
    }
}
